// Boots Pyodide, installs the local `odysseyra_travelbook` wheel (and its
// pure-Python dependency fpdf2 + Pillow), loads the bridge, and exposes one
// typed `call(op, args)` entry point.
//
// This module is **host-agnostic**: it runs inside the Web Worker (the normal
// path, see worker.ts) or on the main thread (the fallback, see runtime.ts). It
// therefore touches no DOM API — `document`/`window` do not exist in a worker.
//
// Pyodide's runtime + core packages are loaded from a version-pinned CDN; the
// service worker (see vite.config.ts) caches them so the app works offline after
// the first load. The `odysseyra_travelbook` wheel itself is served locally and
// precached.
import type { PyodideInterface } from "pyodide"; // type-only (erased at build)
import bridgeSource from "./bridge.py?raw";
import { httpGetSync } from "./netbridge";
import type { BootProgress, EngineCall, Op, OpArgs, OpResult } from "./protocol";
import type { Day, Finding, Itinerary } from "../types/resolved";

const PYODIDE_VERSION = "0.26.4";
const PYODIDE_INDEX_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;

type LoadPyodide = (opts: { indexURL: string }) => Promise<PyodideInterface>;

// Dev-only boot tracing (silent in production builds).
const log = (...args: unknown[]) => {
  if (import.meta.env.DEV) console.info(...args);
};

// Load Pyodide's loader straight from the CDN at runtime rather than importing
// the npm package: bundling `pyodide` through Vite breaks its asset-URL
// resolution (the boot hangs). @vite-ignore keeps this a native dynamic import —
// which is why the worker must be a *module* worker (classic workers can't).
async function importLoadPyodide(): Promise<LoadPyodide> {
  const url = `${PYODIDE_INDEX_URL}pyodide.mjs`;
  log("[boot] importing pyodide.mjs:", url);
  const mod = await import(/* @vite-ignore */ url);
  log("[boot] pyodide.mjs imported; loadPyodide =", typeof mod.loadPyodide);
  return mod.loadPyodide as LoadPyodide;
}

async function wheelUrls(): Promise<string[]> {
  // The manifest lists the local wheels to install (odysseyra_travelbook + its
  // non-Pyodide deps), avoiding hardcoded versioned filenames. Regenerated by
  // scripts/build-wheel.sh.
  const base = import.meta.env.BASE_URL;
  const res = await fetch(`${base}py/wheel.json`);
  if (!res.ok) {
    throw new Error(
      `Missing ${base}py/wheel.json — run \`npm run wheel\` to build the wheels.`,
    );
  }
  const data = (await res.json()) as { wheels?: string[]; wheel?: string };
  const wheels = data.wheels ?? (data.wheel ? [data.wheel] : []);
  return wheels.map((w) => `${base}py/${w}`);
}

export interface Engine {
  call: EngineCall;
}

/** Boot Pyodide and return the engine. Not idempotent — the callers (worker.ts,
 * runtime.ts) each hold the single in-flight promise. */
export async function bootEngine(
  emit: (p: BootProgress) => void = () => {},
): Promise<Engine> {
  emit({ stage: "loading-runtime" });
  const loadPyodide = await importLoadPyodide();
  log("[boot] loadPyodide() starting…");
  const py = await loadPyodide({ indexURL: PYODIDE_INDEX_URL });
  log("[boot] Pyodide runtime ready");

  // Expose the synchronous fetch the maps package uses (bridge.py points
  // `odysseyra_travelbook.maps.http_get` at it). Registered before the bridge is
  // imported so its module-load override picks it up.
  py.registerJsModule("tb_js", { httpGetSync });

  emit({ stage: "installing-packages", detail: "Pillow, fonttools, micropip" });
  // Pillow + fonttools ship with Pyodide (loaded from its CDN, then SW-cached);
  // fpdf2 + defusedxml come from local wheels below. Nothing hits PyPI, so the
  // whole install works offline after the first load.
  // `loadPackage` reports a package it couldn't fetch through `errorCallback`
  // and resolves anyway, so without this a CDN hiccup surfaced much later as a
  // baffling "No module named 'micropip'" from the pyimport below. Collect the
  // failures and fail here, where the message can name the cause.
  const pkgErrors: string[] = [];
  await py.loadPackage(["micropip", "Pillow", "fonttools"], {
    messageCallback: (msg: string) => log("[boot]", msg),
    errorCallback: (msg: string) => {
      pkgErrors.push(msg);
      console.error("[boot] package load failed:", msg);
    },
  });
  if (pkgErrors.length) {
    throw new Error(`Couldn't load the Python packages: ${pkgErrors.join(" | ")}`);
  }
  log("[boot] Pillow + fonttools + micropip loaded");

  emit({ stage: "installing-odysseyra" });
  const micropip = py.pyimport("micropip");
  // Install the local wheels with dependency resolution OFF (deps are already
  // satisfied by Pyodide's packages), so micropip never contacts PyPI.
  await micropip.install.callKwargs(await wheelUrls(), { deps: false });
  log("[boot] odysseyra_travelbook + deps installed");

  // Load the bridge into a module so its functions are reachable via pyimport.
  py.FS.mkdirTree("/bridge");
  py.FS.writeFile("/bridge/odysseyra_bridge.py", bridgeSource);
  py.runPython("import sys; sys.path.insert(0, '/bridge')");
  // Import it once, here rather than per call: the proxy is long-lived (so we
  // don't leak one per operation), and pulling `odysseyra_travelbook` in now
  // means "ready" really means ready — the first render doesn't pay for it.
  const bridge = py.pyimport("odysseyra_bridge");

  emit({ stage: "ready" });
  return { call: (op, args) => dispatch(bridge, op, args) };
}

// The bridge module's proxy. Typed loosely: each attribute is a Python function
// returning a JSON string (or, for `build`, bytes).
type Bridge = Record<string, (...args: unknown[]) => unknown>;

/** Unwrap a bridge reply: every bridge function returns a JSON envelope that
 * either carries the payload under `key` or an `error` string. */
function envelope<T>(raw: string, key: string): T {
  const parsed = JSON.parse(raw) as Record<string, unknown>;
  if (parsed.error) throw new Error(String(parsed.error));
  if (parsed[key] == null) throw new Error(`${key}() returned nothing`);
  return parsed[key] as T;
}

// Every call runs the bridge synchronously: Python is single-threaded, and the
// maps code fetches tiles over a *blocking* XHR (see netbridge.ts). In the
// worker that only blocks the worker, which is the whole point of hosting it
// there — the UI keeps painting its loader.
function dispatch<O extends Op>(bridge: Bridge, op: O, args: OpArgs<O>): OpResult<O> {
  switch (op) {
    case "validate": {
      const [text, lang] = args as OpArgs<"validate">;
      const parsed = JSON.parse(bridge.validate(text, lang) as string) as {
        findings?: Finding[];
        error?: string;
      };
      if (parsed.error) throw new Error(parsed.error);
      return (parsed.findings ?? []) as OpResult<O>;
    }
    case "resolve": {
      const [text] = args as OpArgs<"resolve">;
      return envelope<Itinerary>(bridge.resolve(text) as string, "itinerary") as OpResult<O>;
    }
    case "renderDay": {
      const [text, index] = args as OpArgs<"renderDay">;
      return envelope<Day>(bridge.render_day(text, index) as string, "day") as OpResult<O>;
    }
    case "geocode": {
      const [query, countries] = args as OpArgs<"geocode">;
      const parsed = JSON.parse(bridge.geocode(query, countries) as string) as {
        coordinate?: { lat: number; long: number } | null;
        error?: string;
      };
      if (parsed.error) throw new Error(parsed.error);
      return (parsed.coordinate ?? null) as OpResult<O>;
    }
    case "ics": {
      const [text, lang] = args as OpArgs<"ics">;
      return envelope<string>(bridge.ics(text, lang) as string, "ics") as OpResult<O>;
    }
    case "build": {
      const result = bridge.build(...(args as OpArgs<"build">)) as
        | Uint8Array
        | { toJs: () => Uint8Array; destroy?: () => void };
      // Python `bytes` usually comes back as a PyProxy (needs .toJs()); guard in
      // case a future Pyodide auto-converts it to a Uint8Array.
      if (result instanceof Uint8Array) return new Uint8Array(result) as OpResult<O>;
      const bytes = new Uint8Array(result.toJs() as Uint8Array); // copy out of wasm heap
      result.destroy?.();
      return bytes as OpResult<O>;
    }
  }
  throw new Error(`Unknown engine op: ${String(op)}`);
}
