// Boots Pyodide, installs the local `travelbook` wheel (and its pure-Python
// dependency fpdf2 + Pillow), loads the bridge, and exposes typed wrappers.
//
// Pyodide's runtime + core packages are loaded from a version-pinned CDN; the
// service worker (see vite.config.ts) caches them so the app works offline after
// the first load. The `travelbook` wheel itself is served locally and precached.
import { loadPyodide, type PyodideInterface } from "pyodide";
import bridgeSource from "./bridge.py?raw";
import type { Finding, Itinerary } from "../types/resolved";

const PYODIDE_VERSION = "0.26.4";
const PYODIDE_INDEX_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;

export type Stage =
  | "idle"
  | "loading-runtime"
  | "installing-packages"
  | "installing-travelbook"
  | "ready"
  | "error";

export interface BootProgress {
  stage: Stage;
  detail?: string;
}

type ProgressFn = (p: BootProgress) => void;

let pyodide: PyodideInterface | null = null;
let bootPromise: Promise<PyodideInterface> | null = null;

async function wheelUrl(): Promise<string> {
  // The wheel filename carries the version; a tiny manifest avoids hardcoding it
  // (regenerated by scripts/build-wheel.sh).
  const base = import.meta.env.BASE_URL;
  const res = await fetch(`${base}py/wheel.json`);
  if (!res.ok) {
    throw new Error(
      `Missing ${base}py/wheel.json — run \`npm run wheel\` to build the travelbook wheel.`,
    );
  }
  const { wheel } = (await res.json()) as { wheel: string };
  return `${base}py/${wheel}`;
}

/** Boot Pyodide once (idempotent); resolves when the bridge is ready to call. */
export function boot(onProgress: ProgressFn = () => {}): Promise<PyodideInterface> {
  if (bootPromise) return bootPromise;
  bootPromise = (async () => {
    onProgress({ stage: "loading-runtime" });
    const py = await loadPyodide({ indexURL: PYODIDE_INDEX_URL });

    onProgress({ stage: "installing-packages", detail: "Pillow, micropip" });
    await py.loadPackage(["micropip", "Pillow"]);

    onProgress({ stage: "installing-travelbook" });
    const micropip = py.pyimport("micropip");
    // fpdf2 (+ its pure-Python deps) from PyPI, then the local travelbook wheel.
    await micropip.install("fpdf2");
    await micropip.install(await wheelUrl());

    // Load the bridge into a module so its functions are reachable via pyimport.
    py.FS.mkdirTree("/bridge");
    py.FS.writeFile("/bridge/tb_bridge.py", bridgeSource);
    py.runPython("import sys; sys.path.insert(0, '/bridge')");

    pyodide = py;
    onProgress({ stage: "ready" });
    return py;
  })().catch((err) => {
    bootPromise = null; // allow a retry
    onProgress({ stage: "error", detail: String(err) });
    throw err;
  });
  return bootPromise;
}

function bridge() {
  if (!pyodide) throw new Error("Pyodide is not booted yet — call boot() first.");
  return pyodide.pyimport("tb_bridge");
}

/** Validate raw itinerary JSON; returns findings (throws on a bridge error). */
export async function validate(text: string, lang = "en"): Promise<Finding[]> {
  const raw = bridge().validate(text, lang) as string;
  const parsed = JSON.parse(raw) as { findings?: Finding[]; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  return parsed.findings ?? [];
}

/** Resolve raw itinerary JSON into the render-ready model (throws on error). */
export async function resolve(text: string): Promise<Itinerary> {
  const raw = bridge().resolve(text) as string;
  const parsed = JSON.parse(raw) as { itinerary?: Itinerary; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  if (!parsed.itinerary) throw new Error("resolve() returned no itinerary");
  return parsed.itinerary;
}

/** Build the PDF (maps off in v1). Returns the bytes for download. */
export async function buildPdf(
  text: string,
  opts: { lang?: string; inkSaver?: boolean } = {},
): Promise<Uint8Array> {
  const result = bridge().build(text, opts.lang ?? "en", opts.inkSaver ?? false);
  const bytes = result.toJs() as Uint8Array;
  result.destroy?.();
  return bytes;
}
