// Boots Pyodide, installs the local `travelbook` wheel (and its pure-Python
// dependency fpdf2 + Pillow), loads the bridge, and exposes typed wrappers.
//
// Pyodide's runtime + core packages are loaded from a version-pinned CDN; the
// service worker (see vite.config.ts) caches them so the app works offline after
// the first load. The `travelbook` wheel itself is served locally and precached.
import type { PyodideInterface } from "pyodide"; // type-only (erased at build)
import bridgeSource from "./bridge.py?raw";
import type { Finding, Itinerary } from "../types/resolved";

const PYODIDE_VERSION = "0.26.4";
const PYODIDE_INDEX_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;

type LoadPyodide = (opts: { indexURL: string }) => Promise<PyodideInterface>;

// Dev-only boot tracing (silent in production builds).
const log = (...args: unknown[]) => {
  if (import.meta.env.DEV) console.info(...args);
};

// Load Pyodide's loader straight from the CDN at runtime rather than importing
// the npm package: bundling `pyodide` through Vite breaks its asset-URL
// resolution (the boot hangs). @vite-ignore keeps this a native dynamic import.
async function importLoadPyodide(): Promise<LoadPyodide> {
  const url = `${PYODIDE_INDEX_URL}pyodide.mjs`;
  log("[boot] importing pyodide.mjs:", url);
  const mod = await import(/* @vite-ignore */ url);
  log("[boot] pyodide.mjs imported; loadPyodide =", typeof mod.loadPyodide);
  return mod.loadPyodide as LoadPyodide;
}

export type Stage =
  | "idle"
  | "loading-runtime"
  | "installing-packages"
  | "installing-travelbook"
  | "ready"
  | "error";

export interface BootProgress {
  stage: Stage;
  detail?: string;
}

type ProgressFn = (p: BootProgress) => void;

let pyodide: PyodideInterface | null = null;
let bootPromise: Promise<PyodideInterface> | null = null;

// Progress is broadcast to all subscribers and the latest stage is remembered,
// so a caller that subscribes after boot has started (or re-subscribes — React
// StrictMode double-invokes effects in dev) is replayed the current stage and
// still receives every later update.
let lastProgress: BootProgress = { stage: "idle" };
const progressSubs = new Set<ProgressFn>();

function emit(p: BootProgress) {
  lastProgress = p;
  progressSubs.forEach((fn) => fn(p));
}

async function wheelUrl(): Promise<string> {
  // The wheel filename carries the version; a tiny manifest avoids hardcoding it
  // (regenerated by scripts/build-wheel.sh).
  const base = import.meta.env.BASE_URL;
  const res = await fetch(`${base}py/wheel.json`);
  if (!res.ok) {
    throw new Error(
      `Missing ${base}py/wheel.json — run \`npm run wheel\` to build the travelbook wheel.`,
    );
  }
  const { wheel } = (await res.json()) as { wheel: string };
  return `${base}py/${wheel}`;
}

/** Boot Pyodide once (idempotent); resolves when the bridge is ready to call.
 * Safe to call repeatedly — subsequent callers subscribe to progress and share
 * the one in-flight (or completed) boot. */
export function boot(onProgress: ProgressFn = () => {}): Promise<PyodideInterface> {
  progressSubs.add(onProgress);
  onProgress(lastProgress); // replay the current stage to a late subscriber
  if (bootPromise) return bootPromise;
  bootPromise = (async () => {
    emit({ stage: "loading-runtime" });
    const loadPyodide = await importLoadPyodide();
    log("[boot] loadPyodide() starting…");
    const py = await loadPyodide({ indexURL: PYODIDE_INDEX_URL });
    log("[boot] Pyodide runtime ready");

    emit({ stage: "installing-packages", detail: "Pillow, micropip" });
    await py.loadPackage(["micropip", "Pillow"]);
    log("[boot] Pillow + micropip loaded");

    emit({ stage: "installing-travelbook" });
    const micropip = py.pyimport("micropip");
    // Pin fpdf2 to the version the package is tested against (newer releases
    // import ssl-based urllib handlers that don't exist under Pyodide). Pulled
    // from PyPI with its pure-Python deps, then the local travelbook wheel.
    await micropip.install("fpdf2==2.8.7");
    log("[boot] fpdf2 installed");
    await micropip.install(await wheelUrl());
    log("[boot] travelbook wheel installed");

    // Load the bridge into a module so its functions are reachable via pyimport.
    py.FS.mkdirTree("/bridge");
    py.FS.writeFile("/bridge/tb_bridge.py", bridgeSource);
    py.runPython("import sys; sys.path.insert(0, '/bridge')");

    pyodide = py;
    emit({ stage: "ready" });
    return py;
  })().catch((err) => {
    bootPromise = null; // allow a retry
    emit({ stage: "error", detail: String(err) });
    throw err;
  });
  return bootPromise;
}

function bridge() {
  if (!pyodide) throw new Error("Pyodide is not booted yet — call boot() first.");
  return pyodide.pyimport("tb_bridge");
}

/** Validate raw itinerary JSON; returns findings (throws on a bridge error). */
export async function validate(text: string, lang = "en"): Promise<Finding[]> {
  const raw = bridge().validate(text, lang) as string;
  const parsed = JSON.parse(raw) as { findings?: Finding[]; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  return parsed.findings ?? [];
}

/** Resolve raw itinerary JSON into the render-ready model (throws on error). */
export async function resolve(text: string): Promise<Itinerary> {
  const raw = bridge().resolve(text) as string;
  const parsed = JSON.parse(raw) as { itinerary?: Itinerary; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  if (!parsed.itinerary) throw new Error("resolve() returned no itinerary");
  return parsed.itinerary;
}

/** Build the PDF (maps off in v1). Returns the bytes for download. */
export async function buildPdf(
  text: string,
  opts: { lang?: string; inkSaver?: boolean } = {},
): Promise<Uint8Array> {
  const result = bridge().build(text, opts.lang ?? "en", opts.inkSaver ?? false);
  // Python `bytes` usually comes back as a PyProxy (needs .toJs()); guard in case
  // a future Pyodide auto-converts it to a Uint8Array.
  if (result instanceof Uint8Array) return new Uint8Array(result);
  const bytes = new Uint8Array(result.toJs() as Uint8Array); // copy out of wasm heap
  result.destroy?.();
  return bytes;
}
