// Boots Pyodide, installs the local `travelbook` wheel (and its pure-Python
// dependency fpdf2 + Pillow), loads the bridge, and exposes typed wrappers.
//
// Pyodide's runtime + core packages are loaded from a version-pinned CDN; the
// service worker (see vite.config.ts) caches them so the app works offline after
// the first load. The `travelbook` wheel itself is served locally and precached.
import type { PyodideInterface } from "pyodide"; // type-only (erased at build)
import bridgeSource from "./bridge.py?raw";
import { httpGetSync } from "./netbridge";
import type { Day, Finding, Itinerary } from "../types/resolved";

const PYODIDE_VERSION = "0.26.4";
const PYODIDE_INDEX_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;

type LoadPyodide = (opts: { indexURL: string }) => Promise<PyodideInterface>;

// Dev-only boot tracing (silent in production builds).
const log = (...args: unknown[]) => {
  if (import.meta.env.DEV) console.info(...args);
};

// Load Pyodide's loader straight from the CDN at runtime rather than importing
// the npm package: bundling `pyodide` through Vite breaks its asset-URL
// resolution (the boot hangs). @vite-ignore keeps this a native dynamic import.
async function importLoadPyodide(): Promise<LoadPyodide> {
  const url = `${PYODIDE_INDEX_URL}pyodide.mjs`;
  log("[boot] importing pyodide.mjs:", url);
  const mod = await import(/* @vite-ignore */ url);
  log("[boot] pyodide.mjs imported; loadPyodide =", typeof mod.loadPyodide);
  return mod.loadPyodide as LoadPyodide;
}

export type Stage =
  | "idle"
  | "loading-runtime"
  | "installing-packages"
  | "installing-travelbook"
  | "ready"
  | "error";

export interface BootProgress {
  stage: Stage;
  detail?: string;
}

type ProgressFn = (p: BootProgress) => void;

let pyodide: PyodideInterface | null = null;
let bootPromise: Promise<PyodideInterface> | null = null;

// Progress is broadcast to all subscribers and the latest stage is remembered,
// so a caller that subscribes after boot has started (or re-subscribes — React
// StrictMode double-invokes effects in dev) is replayed the current stage and
// still receives every later update.
let lastProgress: BootProgress = { stage: "idle" };
const progressSubs = new Set<ProgressFn>();

function emit(p: BootProgress) {
  lastProgress = p;
  progressSubs.forEach((fn) => fn(p));
}

async function wheelUrls(): Promise<string[]> {
  // The manifest lists the local wheels to install (travelbook + its
  // non-Pyodide deps), avoiding hardcoded versioned filenames. Regenerated by
  // scripts/build-wheel.sh.
  const base = import.meta.env.BASE_URL;
  const res = await fetch(`${base}py/wheel.json`);
  if (!res.ok) {
    throw new Error(
      `Missing ${base}py/wheel.json — run \`npm run wheel\` to build the wheels.`,
    );
  }
  const data = (await res.json()) as { wheels?: string[]; wheel?: string };
  const wheels = data.wheels ?? (data.wheel ? [data.wheel] : []);
  return wheels.map((w) => `${base}py/${w}`);
}

/** Boot Pyodide once (idempotent); resolves when the bridge is ready to call.
 * Safe to call repeatedly — subsequent callers subscribe to progress and share
 * the one in-flight (or completed) boot. */
export function boot(onProgress: ProgressFn = () => {}): Promise<PyodideInterface> {
  progressSubs.add(onProgress);
  onProgress(lastProgress); // replay the current stage to a late subscriber
  if (bootPromise) return bootPromise;
  bootPromise = (async () => {
    emit({ stage: "loading-runtime" });
    const loadPyodide = await importLoadPyodide();
    log("[boot] loadPyodide() starting…");
    const py = await loadPyodide({ indexURL: PYODIDE_INDEX_URL });
    log("[boot] Pyodide runtime ready");

    // Expose the synchronous fetch the maps package uses (bridge.py points
    // `travelbook.maps.http_get` at it). Registered before the bridge is
    // imported so its module-load override picks it up.
    py.registerJsModule("tb_js", { httpGetSync });

    emit({ stage: "installing-packages", detail: "Pillow, fonttools, micropip" });
    // Pillow + fonttools ship with Pyodide (loaded from its CDN, then SW-cached);
    // fpdf2 + defusedxml come from local wheels below. Nothing hits PyPI, so the
    // whole install works offline after the first load.
    await py.loadPackage(["micropip", "Pillow", "fonttools"]);
    log("[boot] Pillow + fonttools + micropip loaded");

    emit({ stage: "installing-travelbook" });
    const micropip = py.pyimport("micropip");
    // Install the local wheels with dependency resolution OFF (deps are already
    // satisfied by Pyodide's packages), so micropip never contacts PyPI.
    await micropip.install.callKwargs(await wheelUrls(), { deps: false });
    log("[boot] travelbook + deps installed");

    // Load the bridge into a module so its functions are reachable via pyimport.
    py.FS.mkdirTree("/bridge");
    py.FS.writeFile("/bridge/tb_bridge.py", bridgeSource);
    py.runPython("import sys; sys.path.insert(0, '/bridge')");

    pyodide = py;
    emit({ stage: "ready" });
    return py;
  })().catch((err) => {
    bootPromise = null; // allow a retry
    emit({ stage: "error", detail: String(err) });
    throw err;
  });
  return bootPromise;
}

function bridge() {
  if (!pyodide) throw new Error("Pyodide is not booted yet — call boot() first.");
  return pyodide.pyimport("tb_bridge");
}

/** Validate raw itinerary JSON; returns findings (throws on a bridge error). */
export async function validate(text: string, lang = "en"): Promise<Finding[]> {
  const raw = bridge().validate(text, lang) as string;
  const parsed = JSON.parse(raw) as { findings?: Finding[]; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  return parsed.findings ?? [];
}

/** Resolve raw itinerary JSON into the render-ready model (throws on error).
 * Maps are NOT included here — the book renders immediately; each day's map is
 * fetched separately via `renderDayMap` (see App). */
export async function resolve(text: string): Promise<Itinerary> {
  const raw = bridge().resolve(text) as string;
  const parsed = JSON.parse(raw) as { itinerary?: Itinerary; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  if (!parsed.itinerary) throw new Error("resolve() returned no itinerary");
  return parsed.itinerary;
}

/** Render one day's maps and return that day with `day.map` (+ pin labels)
 * merged in, for the UI to swap in place. Fetches tiles synchronously, so it
 * blocks the main thread while running; call it per day between paints. */
export async function renderDayMap(text: string, index: number): Promise<Day> {
  const raw = bridge().render_day(text, index) as string;
  const parsed = JSON.parse(raw) as { day?: Day; error?: string };
  if (parsed.error) throw new Error(parsed.error);
  if (!parsed.day) throw new Error("render_day() returned no day");
  return parsed.day;
}

/** Geocode a free-text address/name to a coordinate via Nominatim (needs the
 * network). `countries` are 2-letter ISO codes narrowing the search. Returns
 * null on no match; throws on a bridge error. */
export async function geocode(
  query: string,
  countries: string[] = [],
): Promise<{ lat: number; long: number } | null> {
  const raw = bridge().geocode(query, countries.join(",")) as string;
  const parsed = JSON.parse(raw) as {
    coordinate?: { lat: number; long: number } | null;
    error?: string;
  };
  if (parsed.error) throw new Error(parsed.error);
  return parsed.coordinate ?? null;
}

/** Build the PDF. `maps` overrides the file's `include_maps_in_render` for this
 * export (undefined leaves the file's own setting in force). Returns the bytes
 * for download. */
export async function buildPdf(
  text: string,
  opts: { lang?: string; inkSaver?: boolean; maps?: boolean } = {},
): Promise<Uint8Array> {
  const result = bridge().build(
    text,
    opts.lang ?? "en",
    opts.inkSaver ?? false,
    opts.maps ?? null,
  );
  // Python `bytes` usually comes back as a PyProxy (needs .toJs()); guard in case
  // a future Pyodide auto-converts it to a Uint8Array.
  if (result instanceof Uint8Array) return new Uint8Array(result);
  const bytes = new Uint8Array(result.toJs() as Uint8Array); // copy out of wasm heap
  result.destroy?.();
  return bytes;
}
